# Generated by Django 2.1.7 on 2019-06-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='company',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AddField(
            model_name='worker',
            name='surname',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(default='name', max_length=200),
        ),
    ]
