# Generated by Django 2.1.7 on 2019-06-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190625_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='job',
            field=models.CharField(choices=[('j1', 'Оператор'), ('j2', 'Менеджер по продажам'), ('j3', 'Фин отдел'), ('j4', 'Бухгалтерия'), ('j5', 'Логисты'), ('j6', 'Продакт Менеджер')], default='pd', max_length=2),
        ),
        migrations.AlterField(
            model_name='worker',
            name='company',
            field=models.CharField(choices=[('pd', 'Planeta Doors'), ('ar', 'ИП Арынов'), ('bt', 'Beltaus Trading')], default='pd', max_length=2),
        ),
    ]
