# Generated by Django 2.1.7 on 2019-06-25 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_laptop'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='laptop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Laptop'),
        ),
    ]
