# Generated by Django 2.1.7 on 2019-06-25 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190625_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
                ('company', models.CharField(choices=[('pd', 'Planeta Doors'), ('ar', 'ИП Арынов'), ('bt', 'Beltaus Trading')], default='pd', max_length=2)),
                ('inventNumber', models.CharField(default='name', max_length=200)),
                ('serialNumber', models.CharField(default='name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
                ('company', models.CharField(choices=[('pd', 'Planeta Doors'), ('ar', 'ИП Арынов'), ('bt', 'Beltaus Trading')], default='pd', max_length=2)),
                ('inventNumber', models.CharField(default='name', max_length=200)),
                ('serialNumber', models.CharField(default='name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
                ('company', models.CharField(choices=[('pd', 'Planeta Doors'), ('ar', 'ИП Арынов'), ('bt', 'Beltaus Trading')], default='pd', max_length=2)),
                ('inventNumber', models.CharField(default='name', max_length=200)),
                ('serialNumber', models.CharField(default='name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shredder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
                ('company', models.CharField(choices=[('pd', 'Planeta Doors'), ('ar', 'ИП Арынов'), ('bt', 'Beltaus Trading')], default='pd', max_length=2)),
                ('inventNumber', models.CharField(default='name', max_length=200)),
                ('serialNumber', models.CharField(default='name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
                ('company', models.CharField(choices=[('pd', 'Planeta Doors'), ('ar', 'ИП Арынов'), ('bt', 'Beltaus Trading')], default='pd', max_length=2)),
                ('inventNumber', models.CharField(default='name', max_length=200)),
                ('serialNumber', models.CharField(default='name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Television',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
                ('company', models.CharField(choices=[('pd', 'Planeta Doors'), ('ar', 'ИП Арынов'), ('bt', 'Beltaus Trading')], default='pd', max_length=2)),
                ('inventNumber', models.CharField(default='name', max_length=200)),
                ('serialNumber', models.CharField(default='name', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='serialNumber',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AddField(
            model_name='printer',
            name='serialNumber',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AlterField(
            model_name='worker',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Printer'),
        ),
    ]
