# Generated by Django 2.1.7 on 2019-06-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190625_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='workerID',
            field=models.IntegerField(default=1),
        ),
    ]
