# Generated by Django 2.0.13 on 2019-06-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190626_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='slug',
        ),
    ]
