# Generated by Django 2.0.13 on 2019-06-27 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_worker_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toxic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
                ('company', models.CharField(choices=[('pd', 'Planeta Doors'), ('ar', 'ИП Арынов'), ('bt', 'Beltaus Trading'), ('ts', 'ИП Таишев'), ('ki', 'ТОО Kendala Impex'), ('co', 'ЦО'), ('un', 'undefined')], default='pd', max_length=2)),
                ('inventNumber', models.CharField(default='name', max_length=200)),
                ('serialNumber', models.CharField(default='name', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='toxic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Toxic'),
        ),
    ]
