# Generated by Django 2.0.13 on 2019-06-27 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190627_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='laptop',
            new_name='userLaptop',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='dispenser',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='printer',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='shredder',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='television',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='toxic',
        ),
        migrations.AddField(
            model_name='laptop',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Worker'),
        ),
    ]
