# Generated by Django 2.0.13 on 2019-06-28 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190627_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='userLaptop',
        ),
        migrations.AddField(
            model_name='printer',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Worker'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Worker'),
        ),
    ]
