# Generated by Django 2.0.13 on 2019-06-28 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190628_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='shredder',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Worker'),
        ),
        migrations.AddField(
            model_name='television',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Worker'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='job',
            field=models.CharField(choices=[('j1', 'Оператор'), ('j2', 'Менеджер по продажам'), ('j3', 'Фин отдел'), ('j4', 'Бухгалтер'), ('j5', 'Логисты'), ('j6', 'Продакт Менеджер'), ('j7', 'Оператор 1С'), ('j8', 'Специалист по кадрам'), ('j9', 'Экономист'), ('k1', 'Коммерческий директор'), ('k2', 'Руководитель отдела продаж'), ('k3', 'Оператор по закупкам'), ('k4', 'Региональный менеджер'), ('k5', 'Кассир'), ('k6', 'Руководитель'), ('k7', 'Руководитель департамента отдела поддержки'), ('k8', 'IT')], default='pd', max_length=2),
        ),
    ]
