# Generated by Django 2.0.13 on 2019-06-28 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190628_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Worker'),
        ),
        migrations.AddField(
            model_name='telephone',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Worker'),
        ),
    ]
