# Generated by Django 2.1 on 2019-07-03 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_condition_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Toxic',
        ),
        migrations.AddField(
            model_name='dispenser',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Worker'),
        ),
    ]
