# Generated by Django 2.1 on 2019-07-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_microwave_refrigerators'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Refrigerators',
            new_name='Refrigerator',
        ),
    ]
