# Generated by Django 2.1 on 2019-07-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190704_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refrigerator',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Refrigerator',
        ),
    ]
