# Generated by Django 2.0.13 on 2019-07-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='adding',
            field=models.BooleanField(default=True, verbose_name='Adding'),
        ),
        migrations.AddField(
            model_name='document',
            name='reading',
            field=models.BooleanField(default=True, verbose_name='Reading'),
        ),
    ]
