# Generated by Django 2.0.13 on 2019-07-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20190711_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='change',
            field=models.BooleanField(default=False, verbose_name='Change'),
        ),
        migrations.AddField(
            model_name='document',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Delete'),
        ),
        migrations.AddField(
            model_name='document',
            name='edit',
            field=models.BooleanField(default=False, verbose_name='Edit'),
        ),
        migrations.AddField(
            model_name='document',
            name='watch',
            field=models.BooleanField(default=False, verbose_name='Watch'),
        ),
        migrations.AlterField(
            model_name='document',
            name='adding',
            field=models.BooleanField(default=False, verbose_name='Adding'),
        ),
        migrations.AlterField(
            model_name='document',
            name='reading',
            field=models.BooleanField(default=False, verbose_name='Reading'),
        ),
    ]
