# Generated by Django 2.0.13 on 2019-07-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20190711_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='fileName',
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.DeleteModel(
            name='FileName',
        ),
    ]
