# Generated by Django 2.0.13 on 2019-07-12 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20190712_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('section', models.CharField(choices=[('s1', 'Справочник'), ('s2', 'Документы'), ('s3', 'Константа'), ('s4', 'План обмена'), ('s5', 'Журнал документов'), ('s6', 'Отчет'), ('s7', 'Обработка'), ('s8', 'План счетов'), ('s9', 'Регистр сведений'), ('s10', 'Регистр накоплений'), ('s11', 'Регистр бухгалтерий')], default='s1', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
        migrations.AddField(
            model_name='document',
            name='fileName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.FileName'),
        ),
    ]
